name: CI

on:
  pull_request:
    branches:
      - main
      - issue-101-cicd
  push:
    branches:
      - main
      - issue-101-cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'

      - name: Run tests
        run: mvn test

  docker:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'

      - name: Copy env.properties
        run: cp env.properties.example env.properties

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Docker Build
        run: docker build -t panagiotisbellias/aeroplanner-rest-api:latest -t panagiotisbellias/aeroplanner-rest-api:0.0.1-SNAPSHOT .

      - name: Docker login
        run: docker login ghcr.io -u panagiotisbellias -p ${{ secrets.REGISTRY_TOKEN }}

      - name: Docker push
        run: docker push ghcr.io/panagiotisbellias/aeroplanner-rest-api --all-tags

#  sonar:
#    runs-on: ubuntu-latest
#
#    needs: test
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#          architecture: 'x64'
#
#      - name: SonarCloud Scan
#        run: mvn sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
