name: CI

on:
  push:
    branches:
      - main
      - issue-101-cicd

jobs:
  setup-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        id: setup-java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'

  build:
    runs-on: ubuntu-latest

    needs: setup-java

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  test:
    runs-on: ubuntu-latest

    needs:
      - setup-java
      - build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: mvn test

  sonar:
    runs-on: ubuntu-latest

    needs:
      - setup-java
      - build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
