version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of the pom.xml file
    schedule:
      interval: "daily" # Check for updates daily
    open-pull-requests-limit: 5 # Limit the number of open PRs
    target-branch: issue-101-cicd
#    ignore:
#      - dependency-name: "io.jsonwebtoken:jjwt-api"
#        versions: ["*"]
#      - dependency-name: "io.jsonwebtoken:jjwt-impl"
#        versions: ["*"]
#      - dependency-name: "io.jsonwebtoken:jjwt-jackson"
#        versions: ["*"]
