name: Updates

on:
  push: # TODO Change to pull_request
    branches:
      - main
      - issue-101-cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'

      - name: Check for dependency updates
        run: mvn versions:display-dependency-updates

      - name: Check for plugin updates
        run: mvn versions:display-plugin-updates

      - name: Update dependencies and plugins
        run: mvn versions:update-properties versions:use-latest-versions
